// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2WzWyHZ4Q7klhqiTg1hZTfYsqHQCrcs',
    appId: '1:258008721524:web:838cf5870011e147b4c921',
    messagingSenderId: '258008721524',
    projectId: 'project-pab-e2bc4',
    authDomain: 'project-pab-e2bc4.firebaseapp.com',
    databaseURL: 'https://project-pab-e2bc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-pab-e2bc4.appspot.com',
    measurementId: 'G-W30VCBBGE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVpUjM-ySB-uC5zLT5cV-Gjmn8Gox9aY',
    appId: '1:258008721524:android:a106368f7e32db1cb4c921',
    messagingSenderId: '258008721524',
    projectId: 'project-pab-e2bc4',
    databaseURL: 'https://project-pab-e2bc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-pab-e2bc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_wDCOGSUIcka2hS9i5vxlGR-jAj_q-w',
    appId: '1:258008721524:ios:83ea33b6e2df8c2ab4c921',
    messagingSenderId: '258008721524',
    projectId: 'project-pab-e2bc4',
    databaseURL: 'https://project-pab-e2bc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-pab-e2bc4.appspot.com',
    iosBundleId: 'com.example.belajarFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_wDCOGSUIcka2hS9i5vxlGR-jAj_q-w',
    appId: '1:258008721524:ios:739e7bbd985f6bb3b4c921',
    messagingSenderId: '258008721524',
    projectId: 'project-pab-e2bc4',
    databaseURL: 'https://project-pab-e2bc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-pab-e2bc4.appspot.com',
    iosBundleId: 'com.example.belajarFirebase.RunnerTests',
  );
}
